### PR TITLE
Fix a bug causing the collector to miss all pods in Kubernetes 0.19.3.

### PR DESCRIPTION
**Pull request by EranGabber**
Also add an explicit debug mode to the setup script, simplify the
setup script, and remove the requirement to provide a path to the
Kubernetes binaries.

Fixes issue #93.

### CODE REVIEW

**Comment by EranGabber** [comment]
The tests failed because Jack broke them. I will fix them in a separate PR.

**Comment by EranGabber** [comment]
This will be fixed in the next PR.

**Comment by jackgr** [comment]
All the tests were passing when I submitted the original PR. I suspect the reason they're breaking is that you've gone back to v1beta3 in the code, but not in the test data. Rather than take the code and the tests back to v1beta3, we really should be leaving them at v1, since v1beta3 is now deprecated and will soon stop working in new deployments.

**Comment by EranGabber** [comment]
I addressed your comments. I tested it on a cluster running Kubernetes 0.19.3. Please take another look. If everything looks good, please merge.

**Comment by jackgr** [comment]
:+1:

**Pull request merged**
