### PR TITLE
Change some 'contains' to 'runs' relations and add 'createdBy' attributes

### PR DESCRIPTION
**Pull request by EranGabber**
Closes issues #7, #25.

### CODE REVIEW

**Comment by EranGabber** [comment]
Supriya,
I addressed your comments. Please take another look.

**Comment by EranGabber** [comment]
Supriya,

I addressed your comment. Please take another look.

Eran

**Comment by supriyagarg** [comment]
Hi Eran,

When I ran the tests in collector_test 7 of them failed. I noticed that they were all due to the compare_to_golden test. It is basically failing due to differences in whitespace used. If you replace the code between lines 71-89 by the following, it will work.


    #Strip the sanitized strings, and replace multiple whitespaces by a single space
    sanitized_golden_data = re.sub('\\s+', ' ', sanitized_golden_data.strip())
    sanitized_ret_value = re.sub('\\s+', ' ', sanitized_ret_value.strip())

    self.assertEqual(sanitized_golden_data, sanitized_ret_value)

**Comment by supriyagarg** [comment]
Eran,

Eran,

Here are my last set of comments for this pull. In utilities.py, when re.match is used in boolean expressions (lines 50 and 204), it should be checked against None to get a boolean value:

    (re.match('^[0-9a-fA-F]+$', x) is not None)

Similarly, in lines 222, and 239, the assertion statements should be: `assert (m is not None)`

**Comment by EranGabber** [comment]
Supriya,

The latest committed code works for me. It does not fail. In any case, I
changed the code according to your suggestion. However, I did not change
the assertion. I explained why the original assertion is superior for
debugging in a new comment.

Eran

**Comment by EranGabber** [comment]
I beg to differ.

The Python documentation says about the result of the re.match() function:

Match objects always have a boolean value of True. Since match() and
search() return None when there is no match, you can test whether there was
a match with a simple if statement:

match = re.search(pattern, string)
if match:
    process(match)

Since the idiomatic way to test for a successful match is:
if re.match(pattern, string):

I prefer to keep it this way.

Eran

**Pull request merged**
