### PR TITLE
Added test assertions for the various subcases of the "contains" relation.

### PR DESCRIPTION
**Pull request by rimey**

### CODE REVIEW

**Comment by supriyagarg** [comment]
I have some minor comments @rimey. Otherwise the tests look good.

**Comment by rimey** [comment]
I added a simple free-form docstring to count_relations() to clarify. Note that this is unit test code, and none of the other helper methods in this same file have docstrings.

**Comment by rimey** [comment]
PTAL

**Comment by supriyagarg** [comment]
Thanks. This looks better. Will merge now.

**Pull request merged**
