### PR TITLE
compute 'timestamp' values correctly

### PR DESCRIPTION
**Pull request by EranGabber**
This is the remaining code and unit tests for implementing #81.

### CODE REVIEW

**Comment by supriyagarg** [comment]
@EranGabber : I have reviewed all the changes. There are some minor comments. PTAL.

**Comment by supriyagarg** [comment]
I don't see a new commit with the changes yet - please check.

**Comment by EranGabber** [comment]
Sorry about that. My changes should be visible now.

Eran

**Comment by supriyagarg** [comment]
Thanks. The changes look good.

**Pull request merged**
