### PR TITLE
Create service and controller deployment specs for v2.

### PR DESCRIPTION
**Pull request by rimey**
The minion controller is gone, of course. To keep things simple,
there is no separate controller for debug mode.

The controller spec presumes that a Docker image will appear soon
at kubernetes/cluster-insight:v2.0-alpha.

Note that the setup shell script is not current.

### CODE REVIEW

**Comment by supriyagarg** [comment]
@rimey - if you can upload the cluster-insight image v2.0-alpha, I can test the new controller/service specs.

Thanks.

**Comment by rimey** [comment]
Wait on merging this pull request. I'll update the README. You can test the new instructions while you're at it.

**Comment by supriyagarg** [comment]
Sure.

**Comment by rimey** [comment]
kubernetes/cluster-insight:v2.0-alpha has been uploaded to Docker Hub.

I appreciate the simplicity of ISO dates as version names, but now that we have two incompatible major versions, we should adopt semantic versioning as the Kubernetes projects have done.

**Pull request merged**
